version: '3.8'
services:
  web:
    image: chialab/php:8.2-apache
    container_name: meghbelaweb_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=lcn_db
      - DB_PORT=3306
      - DB_DATABASE=meghbela_lcn_db_kol
      - DB_USERNAME=md_dbuser
      - DB_PASSWORD=m#gh@c@s
    depends_on:
      - lcn_db
    ports:
      - "8080:80"
    command: >
      sh -c "composer install --no-dev --optimize-autoloader && \
             php artisan config:cache && \
             php artisan route:cache && \
             php artisan view:cache && \
             php artisan migrate --force && \
             apache2-foreground"

  # Reference to the existing MySQL container (do not recreate)
  lcn_db:
    external: true

volumes:
  mysql_data:
    external: true 